"""Agentic OS — Plugin Hub: one catalog over every plugin source.

WHY THIS EXISTS
───────────────
Module 19 found the platform running TWO parallel, unaware plugin systems:

  /api/plugins/*     4 built-in skill packs, install state in plugins/installed.json
  /api/marketplace/* 8 curated packs,       install state in the mkt_installs table

They overlap ("research-assistant" exists in both, with different skills), they
render in different panes, and installing from one leaves the other showing the
pack as available. A user asking "what's installed?" had to check two places and
reconcile the answers themselves.

That is the opposite of how ChatGPT's GPT store, Claude's connector directory or
Manus's tool catalog work: ONE browsable surface, one install button, one list of
what you have, and an obvious "what does this actually do" preview before you
commit.

This router is that single surface. It does not replace either backend — both
keep working, and their own endpoints are untouched — it federates them:

    GET  /api/hub/catalog       every pack from every source, normalised
    GET  /api/hub/installed     one list, regardless of which backend owns it
    GET  /api/hub/pack/{id}     full detail incl. the actual skills and prompts
    POST /api/hub/install/{id}  routes to the right backend automatically
    POST /api/hub/uninstall/{id}
    GET  /api/hub/collections   curated starter bundles ("Getting Started", ...)

Normalisation matters more than it sounds: the two backends disagree on field
names for the same concept (emoji/icon, version/latest_ver, skill_count computed
two different ways). The UI previously had to know which backend a card came
from in order to render it. Now it does not.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

router = APIRouter(prefix='/api/hub', tags=['plugin-hub'])
log = logging.getLogger('agentic.hub')

SOURCE_PLUGINS = 'plugins'
SOURCE_MARKET = 'marketplace'


# ── Normalisation ──────────────────────────────────────────────────────────────
def _norm_from_plugins(p: dict, installed_ids: set[str]) -> dict:
    """Normalise a /api/plugins registry entry."""
    skills = p.get('skills') or []
    return {
        'id': p.get('id', ''),
        'source': SOURCE_PLUGINS,
        'name': p.get('name', ''),
        'description': p.get('description', ''),
        'icon': p.get('emoji') or '🧩',
        'author': p.get('author') or 'Community',
        'category': p.get('category') or 'general',
        'version': p.get('version') or '1.0.0',
        'tags': p.get('tags') or [],
        'skill_count': p.get('skill_count') if p.get('skill_count') is not None else len(skills),
        'installed': p.get('id') in installed_ids,
        'verified': p.get('author') == 'Agentic OS',
        'downloads': p.get('downloads', 0),
        'rating': p.get('rating', 0),
    }


def _norm_from_market(p: dict, installed_ids: set[str]) -> dict:
    """Normalise a /api/marketplace pack."""
    skills = p.get('skills') or []
    return {
        'id': p.get('id', ''),
        'source': SOURCE_MARKET,
        'name': p.get('name', ''),
        'description': p.get('description', ''),
        'icon': p.get('icon') or '📦',
        'author': p.get('author') or 'Community',
        'category': p.get('category') or 'general',
        'version': p.get('latest_ver') or '1.0.0',
        'tags': p.get('tags_list') or [],
        'skill_count': p.get('skill_count') if p.get('skill_count') is not None else len(skills),
        'installed': p.get('id') in installed_ids,
        'verified': bool(p.get('verified')),
        'downloads': p.get('downloads', 0),
        'rating': p.get('rating', 0),
    }


# Ids and names generated by the test suites. Test residue in the plugin
# registry is not merely untidy here: the hub is the platform's shop window, and
# a first-run user seeing "🧪 sysplugin_928ffc841e" next to "Social Media Pack"
# learns that the catalog is not curated. The unit suite is sandboxed as of
# 1b07a0f, but rows already written to plugins/installed.json persist, and the
# live-server suites still exercise these endpoints against a real registry.
_TEST_ID_PREFIXES = ('test_plugin_', 'sysplugin_', 'uat_plugin_', 'regress_', 'e2e_plugin_')
_TEST_CATEGORIES = {'testing'}


def _is_test_artifact(entry: dict) -> bool:
    pid = str(entry.get('id', ''))
    if pid.startswith(_TEST_ID_PREFIXES):
        return True
    return entry.get('category') in _TEST_CATEGORIES and entry.get('skill_count', 0) == 0


def _plugins_catalog() -> list[dict]:
    from .plugins import BUILTIN_REGISTRY, _load_installed

    installed = set(_load_installed().keys())
    return [_norm_from_plugins(p, installed) for p in BUILTIN_REGISTRY]


def _market_catalog() -> list[dict]:
    from ..services.memory_db import get_conn
    from .marketplace import _pack_row_to_dict

    con = get_conn()
    try:
        rows = con.execute('SELECT * FROM mkt_packs WHERE published=1').fetchall()
        installed = {
            r[0] for r in con.execute('SELECT pack_id FROM mkt_installed').fetchall()
        }
    except Exception as e:
        log.warning('hub: marketplace unavailable: %s', e)
        return []
    finally:
        con.close()
    return [_norm_from_market(_pack_row_to_dict(r), installed) for r in rows]


def _full_catalog() -> list[dict]:
    """Both sources, de-duplicated by id.

    When the same id exists in both (e.g. "research-assistant"), the entry with
    more skills wins and the other is dropped — showing the user the same pack
    twice, with different contents and independent install buttons, is exactly
    the confusion this router exists to remove.
    """
    merged: dict[str, dict] = {}
    for item in _plugins_catalog() + _market_catalog():
        pid = item['id']
        if not pid or _is_test_artifact(item):
            continue
        prev = merged.get(pid)
        if prev is None:
            merged[pid] = item
            continue
        # Prefer whichever is installed; then whichever has more content.
        if item['installed'] and not prev['installed'] or item['installed'] == prev['installed'] and item['skill_count'] > prev['skill_count']:
            merged[pid] = item
    return sorted(
        merged.values(),
        key=lambda x: (not x['installed'], -x.get('downloads', 0), x['name'].lower()),
    )


# ── Curated starter collections ────────────────────────────────────────────────
# The "I just installed this, now what?" problem. An empty catalog search box is
# a worse first run than three obvious buttons.
COLLECTIONS = [
    {
        'id': 'getting-started',
        'name': 'Getting Started',
        'description': 'The essentials. Install this first — summarise, explain, write, and review.',
        'icon': '🚀',
        'packs': ['agenticai-core', 'content-creator'],
        'recommended': True,
    },
    {
        'id': 'developer',
        'name': 'For Developers',
        'description': 'Code review, refactoring, API design, tests, and DevOps runbooks.',
        'icon': '💻',
        'packs': ['dev-toolkit', 'code-wizard', 'devops-toolkit'],
        'recommended': True,
    },
    {
        'id': 'creator',
        'name': 'For Creators & Marketers',
        'description': 'Social posts, long-form content, SEO, and campaign copy.',
        'icon': '🎨',
        'packs': ['social-media-pack', 'content-creator'],
        'recommended': True,
    },
    {
        'id': 'founder',
        'name': 'For Founders',
        'description': 'Pitch decks, market research, customer success, and analytics.',
        'icon': '📈',
        'packs': ['founder-os', 'data-analyst', 'customer-success'],
        'recommended': False,
    },
    {
        'id': 'researcher',
        'name': 'For Researchers',
        'description': 'Literature review, source comparison, structured summarisation.',
        'icon': '🔬',
        'packs': ['research-assistant', 'prompt-engineering'],
        'recommended': False,
    },
]


# ── Endpoints ──────────────────────────────────────────────────────────────────
@router.get('/catalog')
def catalog(q: str = '', category: str = '', installed: str = ''):
    """Every plugin from every source, normalised into one shape."""
    items = _full_catalog()

    if q:
        needle = q.lower()
        items = [
            i for i in items
            if needle in i['name'].lower()
            or needle in i['description'].lower()
            or any(needle in str(t).lower() for t in i['tags'])
        ]
    if category:
        items = [i for i in items if i['category'] == category]
    if installed == 'true':
        items = [i for i in items if i['installed']]
    elif installed == 'false':
        items = [i for i in items if not i['installed']]

    return {
        'ok': True,
        'items': items,
        'total': len(items),
        'categories': sorted({i['category'] for i in _full_catalog() if i['category']}),
    }


@router.get('/installed')
def installed_list():
    """One list of what the user has, regardless of which backend owns it."""
    items = [i for i in _full_catalog() if i['installed']]
    return {'ok': True, 'items': items, 'total': len(items)}


@router.get('/collections')
def collections():
    """Curated bundles, annotated with live install state."""
    cat = {i['id']: i for i in _full_catalog()}
    out = []
    for c in COLLECTIONS:
        packs = [cat[p] for p in c['packs'] if p in cat]
        out.append({
            **c,
            'packs': packs,
            'available': len(packs),
            'installed_count': sum(1 for p in packs if p['installed']),
            'skill_total': sum(p['skill_count'] for p in packs),
        })
    return {'ok': True, 'collections': out}


@router.get('/pack/{pack_id}')
def pack_detail(pack_id: str):
    """Full detail INCLUDING the actual skills and their prompt templates.

    "What does this actually do before I install it" was unanswerable: the
    /api/plugins registry endpoint explicitly strips skills (`'skills': None`),
    so the only way to find out was to install the pack and go look in the
    Skills pane.
    """
    entry = next((i for i in _full_catalog() if i['id'] == pack_id), None)
    if not entry:
        return JSONResponse({'ok': False, 'error': 'Plugin not found'}, status_code=404)

    skills: list[dict] = []
    if entry['source'] == SOURCE_PLUGINS:
        from .plugins import BUILTIN_REGISTRY

        raw = next((p for p in BUILTIN_REGISTRY if p['id'] == pack_id), None)
        skills = (raw or {}).get('skills') or []
    else:
        from .marketplace import get_pack

        detail = get_pack(pack_id)
        if isinstance(detail, dict):
            skills = detail.get('skills') or []

    return {
        'ok': True,
        **entry,
        'skills': [
            {
                'id': s.get('id'),
                'name': s.get('name'),
                'emoji': s.get('emoji', '⚡'),
                'description': s.get('description', ''),
                'inputs': s.get('inputs', []),
                'prompt_template': s.get('prompt_template', ''),
            }
            for s in skills
            if isinstance(s, dict)
        ],
        'skill_count': len(skills),
    }


@router.post('/install/{pack_id}')
async def install(pack_id: str, req: Request):
    """Install from whichever backend owns the pack. One button, either source."""
    entry = next((i for i in _full_catalog() if i['id'] == pack_id), None)
    if not entry:
        return JSONResponse({'ok': False, 'error': 'Plugin not found'}, status_code=404)
    if entry['installed']:
        return JSONResponse(
            {'ok': False, 'error': f"{entry['name']} is already installed", 'installed': True},
            status_code=409,
        )

    if entry['source'] == SOURCE_PLUGINS:
        from .plugins import install_plugin

        result = await install_plugin(pack_id, req)
    else:
        from .marketplace import install_pack

        result = await install_pack(pack_id, req)

    if isinstance(result, JSONResponse):
        return result
    if not isinstance(result, dict) or not result.get('ok'):
        return JSONResponse(
            {'ok': False, 'error': (result or {}).get('error', 'Install failed')}, status_code=400
        )

    added = result.get('skills_added', result.get('skills', 0))
    return {
        'ok': True,
        'id': pack_id,
        'name': entry['name'],
        'source': entry['source'],
        'skills_added': added,
        'message': f"Installed {entry['name']} — {added} skill(s) ready in Skills",
    }


@router.post('/uninstall/{pack_id}')
def uninstall(pack_id: str):
    """Uninstall, routing to the owning backend."""
    entry = next((i for i in _full_catalog() if i['id'] == pack_id), None)
    if not entry:
        return JSONResponse({'ok': False, 'error': 'Plugin not found'}, status_code=404)
    if not entry['installed']:
        return JSONResponse(
            {'ok': False, 'error': f"{entry['name']} is not installed"}, status_code=409
        )

    if entry['source'] == SOURCE_PLUGINS:
        from .plugins import uninstall_plugin

        result = uninstall_plugin(pack_id)
    else:
        from .marketplace import uninstall_pack

        result = uninstall_pack(pack_id)

    if isinstance(result, JSONResponse):
        return result
    return {'ok': True, 'id': pack_id, 'name': entry['name'], 'detail': result}


@router.post('/collections/{collection_id}/install')
async def install_collection(collection_id: str, req: Request):
    """Install every pack in a starter collection in one action."""
    coll = next((c for c in COLLECTIONS if c['id'] == collection_id), None)
    if not coll:
        return JSONResponse({'ok': False, 'error': 'Collection not found'}, status_code=404)

    results, added_total, failed = [], 0, []
    for pid in coll['packs']:
        entry = next((i for i in _full_catalog() if i['id'] == pid), None)
        if not entry:
            continue
        if entry['installed']:
            results.append({'id': pid, 'status': 'already_installed'})
            continue
        r = await install(pid, req)
        if isinstance(r, JSONResponse):
            failed.append(pid)
            results.append({'id': pid, 'status': 'failed'})
        else:
            added_total += r.get('skills_added', 0) or 0
            results.append({'id': pid, 'status': 'installed', 'skills': r.get('skills_added', 0)})

    return {
        'ok': not failed,
        'collection': coll['name'],
        'results': results,
        'skills_added': added_total,
        'failed': failed,
        'message': f"{coll['name']}: {added_total} skill(s) added",
    }


@router.get('/updates')
def updates():
    """Packs with a newer version than the one installed.

    mkt_releases and /marketplace/installed/check-updates already existed but
    nothing surfaced them, so an installed pack could go stale indefinitely.
    """
    out: list[dict] = []
    try:
        from .marketplace import check_updates

        for u in (check_updates() or {}).get('updates', []):
            out.append({
                'id': u.get('pack_id'), 'name': u.get('name'),
                'icon': u.get('icon') or '📦',
                'installed_version': u.get('installed_ver'),
                'latest_version': u.get('latest_ver'), 'source': SOURCE_MARKET,
            })
    except Exception as e:  # pragma: no cover
        log.warning('hub: update check failed: %s', e)

    try:
        from .plugins import BUILTIN_REGISTRY, _load_installed

        for pid, rec in _load_installed().items():
            pack = next((p for p in BUILTIN_REGISTRY if p.get('id') == pid), None)
            if not pack:
                continue
            latest = pack.get('version') or '1.0.0'
            if rec.get('version') and rec['version'] != latest:
                out.append({
                    'id': pid, 'name': pack.get('name', pid),
                    'icon': pack.get('emoji') or '🧩',
                    'installed_version': rec.get('version'),
                    'latest_version': latest, 'source': SOURCE_PLUGINS,
                })
    except Exception as e:  # pragma: no cover
        log.warning('hub: plugin update check failed: %s', e)

    seen, uniq = set(), []
    for u in out:
        if u['id'] in seen:
            continue
        seen.add(u['id'])
        uniq.append(u)
    return {'ok': True, 'updates': uniq, 'count': len(uniq)}


@router.get('/provenance/{pack_id}')
def provenance(pack_id: str):
    """Where an installed pack came from, and its content hash.

    Custom plugins arrive from an arbitrary URL or a paste and were previously
    indistinguishable from curated content once installed.
    """
    from .plugins import _load_installed

    rec = _load_installed().get(pack_id)
    if not rec:
        return JSONResponse({'ok': False, 'error': 'Not installed'}, status_code=404)
    return {
        'ok': True, 'id': pack_id,
        'origin': rec.get('origin', 'unknown'),
        'origin_url': rec.get('origin_url', ''),
        'content_hash': rec.get('content_hash', ''),
        'installed_at': rec.get('installed_at', ''),
        'warnings': rec.get('warnings', []),
        'trusted': rec.get('origin') == 'builtin',
    }


@router.post('/review')
async def review_before_install(req: Request):
    """Static safety review of a pack WITHOUT installing it."""
    try:
        body = await req.json()
    except Exception:
        body = {}
    pack = body.get('plugin_json') or body.get('pack') or body
    if not isinstance(pack, dict):
        return JSONResponse({'ok': False, 'error': 'Expected a plugin object'}, status_code=400)

    from ..services.plugin_safety import review_pack

    return {'ok': True, **review_pack(pack)}


@router.get('/stats')
def stats():
    """Headline numbers for the hub landing page."""
    items = _full_catalog()
    inst = [i for i in items if i['installed']]
    return {
        'ok': True,
        'total_packs': len(items),
        'installed_packs': len(inst),
        'available_skills': sum(i['skill_count'] for i in items),
        'installed_skills': sum(i['skill_count'] for i in inst),
        'categories': len({i['category'] for i in items}),
    }
