#!/usr/bin/env python3
"""Remove test residue from workspaces/ and the workspaces DB table.

WHY THIS EXISTS
───────────────
tests/unit/conftest.py sandboxed the DATABASE (AGENTIC_TEST_DB) but not the
FILESYSTEM, so every unit run that created a workspace wrote into the real
repo. Measured before the fix:

    workspaces/ on disk          1158 directories
    tracked by git               3135 files
    rows in the workspaces table  618

Of those 618, exactly ONE is a genuine user project ("My Project"). The rest
are named UnitWS_*, ActivateWS_*, SysWS_*, "Regress WS Activate", or are
security-probe payloads such as "' OR '1'='1'; DROP TABLE agents; --" and
"<script>alert(document.cookie)</script>" left by injection tests. The user's
real workspace list was unusable.

The conftest fix stops new residue. This removes the accumulated backlog.

SAFETY
──────
Deletion is opt-in (--apply); the default is a dry run that prints exactly what
would go. Anything not confidently identified as test output is KEPT — the cost
of leaving a stray test workspace is cosmetic, the cost of deleting a real
project is not. The active workspace is never deleted.

    python3 scripts/clean_test_residue.py            # dry run
    python3 scripts/clean_test_residue.py --apply    # actually delete
"""

from __future__ import annotations

import argparse
import re
import shutil
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WS_DIR = ROOT / 'workspaces'
DB = ROOT / 'memory' / 'agentic.db'

# Names generated by the test suites. Anchored at the start so a real project
# called "Regression Analysis Tool" is not swept up by a bare substring match.
TEST_NAME_PATTERNS = (
    r'^UnitWS_', r'^WSID_', r'^SaveWS_', r'^UnitTestWS_', r'^ActivateWS_',
    r'^ActivateTestWS', r'^SysWS_', r'^Regress\b', r'^TestWS', r'^E2E\b',
    r'^UAT\b', r'^Flow\d', r'^Perf\b', r'^Concurrency', r'^Integ\b',
    r'^M18 ', r'^XSwitchTest', r'^UpdatedWorkspace$', r'^New Project$',
)

# Exact names left by boundary/injection tests.
TEST_EXACT_NAMES = {
    '123', 'x', 'test', 'Test', 'foo', 'bar', 'Renamed', '日本語',
    'Client A Site', 'M18 other', 'M18 shared', 'M18 swap',
}

# Payloads from the security tests. These are unmistakably not user projects.
INJECTION_MARKERS = (
    'DROP TABLE', '<script', '$(', '`id`', '../../', 'OR \'1\'=\'1\'',
    'alert(', 'passwd',
)

_TEST_RE = re.compile('|'.join(TEST_NAME_PATTERNS), re.IGNORECASE)

# Non-workspace directories that legitimately live under workspaces/.
RESERVED_DIRS = {
    'specs', 'workflows', 'collab_docs', 'rag_documents', 'marketplace',
    'plugin_sdk', 'obsidian', 'canvas',
}


def is_test_workspace(name: str) -> bool:
    name = (name or '').strip()
    if not name:
        return True
    if name in TEST_EXACT_NAMES:
        return True
    if _TEST_RE.search(name):
        return True
    return any(m.lower() in name.lower() for m in INJECTION_MARKERS)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--apply', action='store_true', help='actually delete (default: dry run)')
    args = ap.parse_args()

    if not DB.exists():
        print(f'No database at {DB}', file=sys.stderr)
        return 1

    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    rows = con.execute('SELECT id, name, is_active FROM workspaces').fetchall()

    current = ''
    cur_file = WS_DIR / '.current'
    if cur_file.exists():
        current = cur_file.read_text().strip()

    doomed, kept = [], []
    for r in rows:
        if r['id'] == current or r['is_active']:
            kept.append((r['id'], r['name'], 'ACTIVE'))
        elif is_test_workspace(r['name']):
            doomed.append((r['id'], r['name']))
        else:
            kept.append((r['id'], r['name'], 'keep'))

    known_ids = {r['id'] for r in rows}
    orphan_dirs = [
        d for d in (WS_DIR.iterdir() if WS_DIR.exists() else [])
        if d.is_dir() and d.name not in RESERVED_DIRS and d.name not in known_ids
    ]

    print(f'Database rows      : {len(rows)}')
    print(f'  test residue     : {len(doomed)}')
    print(f'  keeping          : {len(kept)}')
    print(f'Orphan directories : {len(orphan_dirs)}  (on disk, no DB row)')
    print()
    print('KEEPING:')
    for wid, name, why in kept:
        print(f'  [{why:6}] {wid}  {name!r}')

    if not args.apply:
        print()
        print(f'DRY RUN — would delete {len(doomed)} rows and '
              f'{len(doomed) + len(orphan_dirs)} directories.')
        print('Re-run with --apply to perform the deletion.')
        con.close()
        return 0

    removed_dirs = 0
    for wid, _name in doomed:
        target = WS_DIR / wid
        # Containment check: wid comes from the DB, but this script deletes
        # trees, so it verifies rather than trusts.
        if target.is_dir() and target.resolve().parent == WS_DIR.resolve():
            shutil.rmtree(target, ignore_errors=True)
            removed_dirs += 1
        con.execute('DELETE FROM workspaces WHERE id=?', (wid,))

    for d in orphan_dirs:
        if d.resolve().parent == WS_DIR.resolve():
            shutil.rmtree(d, ignore_errors=True)
            removed_dirs += 1

    con.commit()
    con.close()
    print()
    print(f'Deleted {len(doomed)} database rows and {removed_dirs} directories.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
