"""What the browser console says while the app is used.

WHY THIS DIMENSION HAD NEVER BEEN MEASURED
──────────────────────────────────────────
Twenty audits inspect the DOM, the network and the rendered pixels. **None of
them had ever read the console** — the one channel where the browser itself
reports what the application got wrong. It was being discarded on every run.

THE DEFECT: NO FAVICON, AND A PWA MANIFEST POINTING AT NOTHING
──────────────────────────────────────────────────────────────
`GET /favicon.ico` returned **404 on every single page load**. Browsers request
it unprompted, so every visit logged a failure.

Pulling that thread found worse: `manifest.json` advertised
`/static/icon-192.png` and `/static/icon-512.png`, and **neither file existed**.
The app could be installed as a PWA only without an icon — a blank tile on the
home screen.

Three icons are now committed (`frontend/icon-192.png`, `icon-512.png`,
`favicon.ico` + `favicon.png`), generated by a dependency-free stdlib script
rather than adding an image library for three static files — the same
constraint `scripts/build_bundle.py` was written under. `/favicon.ico` has a
route, and the document head declares all three.

WHY IT WENT UNNOTICED FOR THE WHOLE REVIEW
──────────────────────────────────────────
The console carries **~11,000 messages per session**, essentially all of them
CSP `style-src` refusals. Those are expected and harmless — `style-src 'self'`
refuses the parser-level `style` attribute and `00-style-hydrate.js` re-applies
each one through the CSSOM, where CSP does not reach. Verified directly during
this batch: of the visible elements carrying a `style` attribute, **0 had
dropped declarations**. Nothing is broken on screen.

But a console with 11,000 expected lines in it is a console nobody reads, and a
404 on every page load sat there in plain sight for 58 module reviews. That is
why NOISE is counted and budgeted as its own number: **noise is the condition
that hides the next real bug**, so it is worth a measurement even though it is
not itself a defect.

Two real errors, zero page errors and 11,004 noise messages is a healthier
result than it sounds — but only because the noise is now bounded and watched.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
FRONTEND = REPO / 'frontend'
AUDIT = REPO / 'scripts' / 'audit'
SRC = (AUDIT / 'console_health.py').read_text(encoding='utf-8')
APP = (REPO / 'backend' / 'app.py').read_text(encoding='utf-8')
HTML = (FRONTEND / 'index.html').read_text(encoding='utf-8')


# ──────────────────────────────────────────────────────────────────────
#  The icons exist
# ──────────────────────────────────────────────────────────────────────
def test_favicon_file_exists():
    """404 on every page load, for the entire review, hidden by console noise."""
    assert (FRONTEND / 'favicon.ico').is_file()


def test_manifest_icons_exist():
    """The manifest promised two PNGs that were never in the repo, so the PWA
    installed with a blank tile."""
    manifest = json.loads((FRONTEND / 'manifest.json').read_text(encoding='utf-8'))
    for icon in manifest.get('icons', []):
        src = icon['src'].replace('/static/', '')
        assert (FRONTEND / src).is_file(), f'{icon["src"]} is advertised but missing'


def test_shortcut_icons_exist():
    """Shortcuts carry their own icon list, easily missed."""
    manifest = json.loads((FRONTEND / 'manifest.json').read_text(encoding='utf-8'))
    for shortcut in manifest.get('shortcuts', []):
        for icon in shortcut.get('icons', []):
            src = icon['src'].replace('/static/', '')
            assert (FRONTEND / src).is_file(), f'{icon["src"]} missing'


def test_the_icons_are_valid_pngs_of_the_declared_size():
    """A file that exists but is not a real PNG fixes the 404 and leaves a
    broken image, which is a worse outcome than the 404."""
    manifest = json.loads((FRONTEND / 'manifest.json').read_text(encoding='utf-8'))
    for icon in manifest.get('icons', []):
        path = FRONTEND / icon['src'].replace('/static/', '')
        data = path.read_bytes()
        assert data[:8] == b'\x89PNG\r\n\x1a\n', f'{path.name} is not a PNG'
        width, height = struct.unpack('>II', data[16:24])
        declared = int(icon['sizes'].split('x')[0])
        assert (width, height) == (declared, declared), (
            f'{path.name} is {width}x{height}, manifest says {icon["sizes"]}')


def test_favicon_ico_wraps_a_real_image():
    data = (FRONTEND / 'favicon.ico').read_bytes()
    reserved, kind, count = struct.unpack('<HHH', data[:6])
    assert reserved == 0 and kind == 1 and count >= 1, 'not a valid ICO header'
    assert b'\x89PNG\r\n\x1a\n' in data, 'ICO carries no image payload'


# ──────────────────────────────────────────────────────────────────────
#  They are wired up
# ──────────────────────────────────────────────────────────────────────
def test_favicon_route_is_served():
    """The file existing is not enough: /favicon.ico is requested at the root,
    not under /static."""
    assert "@app.get('/favicon.ico'" in APP


def test_document_head_declares_the_icons():
    assert 'rel="icon"' in HTML
    assert 'apple-touch-icon' in HTML


# ──────────────────────────────────────────────────────────────────────
#  The probe
# ──────────────────────────────────────────────────────────────────────
def test_the_probe_listens_on_both_channels():
    """An uncaught exception does not always surface as a console message of
    type `error`; `pageerror` is a separate Playwright event."""
    assert "page.on('pageerror'" in SRC
    assert "page.on('console'" in SRC


def test_the_probe_budgets_noise_separately_from_errors():
    """Noise is not a defect, but it is the condition that hides the next
    one -- so it gets a number rather than being ignored."""
    assert 'NOISE_BUDGET' in SRC
    assert 'PAGE-ERROR' in SRC
    assert 'CONSOLE-ERROR' in SRC


def test_expected_messages_are_enumerated_not_pattern_swallowed():
    """A blanket "ignore errors" filter would have hidden the favicon 404 for
    the same reason the noise did."""
    assert 'EXPECTED' in SRC
    assert 'Content Security Policy' in SRC


def test_failed_subresources_are_matched_by_url_not_message():
    """"Failed to load resource: ... 404" carries NO url in the message text,
    so it cannot be matched against the exempt list. The response event does."""
    assert "page.on('response'" in SRC
    assert 'expected_404' in SRC


def test_only_as_many_404_lines_are_dropped_as_were_exempt():
    """Removing every "Failed to load resource" line wholesale would have
    swallowed the favicon 404 -- the actual bug in this batch."""
    assert 'remaining -= 1' in SRC


def test_the_audit_is_registered():
    assert 'console_health' in (AUDIT / 'run_all.py').read_text(encoding='utf-8')
    ratchet = (REPO / 'tests' / 'unit' / 'test_120_audit_ratchet.py').read_text(
        encoding='utf-8')
    assert "('console_health', 'console-health')" in ratchet
    baseline = json.loads((AUDIT / 'baseline.json').read_text(encoding='utf-8'))
    assert baseline.get('console-health') == 0
